// <auto-generated />
using System;
using FolderCleaner.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FolderCleaner.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220301063512_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FolderCleaner.Models.CleanerHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CleanerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CleanerStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CleanerStatusDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CleanerId");

                    b.ToTable("CleanerHistories");
                });

            modelBuilder.Entity("FolderCleaner.Models.CleanerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorksAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cleaners");
                });

            modelBuilder.Entity("FolderCleaner.Models.CleanerHistoryModel", b =>
                {
                    b.HasOne("FolderCleaner.Models.CleanerModel", "CleanerModel")
                        .WithMany("CleanerHistories")
                        .HasForeignKey("CleanerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
